# Generated by Django 4.1.4 on 2022-12-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pattes', models.IntegerField()),
                ('poid', models.IntegerField()),
                ('taille', models.IntegerField()),
                ('vitess', models.IntegerField()),
                ('famille', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
