# Generated by Django 4.1.5 on 2023-01-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField()),
                ('cout', models.IntegerField()),
                ('taille', models.IntegerField()),
                ('photo', models.ImageField(default='img_chambre/default.jpg', upload_to='img_chambre', verbose_name='photo de chambre')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='type_chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_location', models.DateTimeField()),
                ('date_retour', models.DateTimeField()),
                ('cout', models.IntegerField()),
                ('statu', models.BooleanField(default=0)),
                ('chambre_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Hotel.chambre')),
                ('client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Hotel.client')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='type_chambre_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Hotel.type_chambre'),
        ),
        migrations.CreateModel(
            name='avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.CharField(max_length=30)),
                ('client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Hotel.client')),
            ],
        ),
    ]
